"use strict";
const SOURCES=[{label:"FIFA player statistics via Jina Reader",url:"https://r.jina.ai/https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/statistics/player-statistics",parser:"fifa"},{label:"FIFA statistics overview via Jina Reader",url:"https://r.jina.ai/https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/statistics",parser:"fifa"},{label:"Jina Search fallback",url:"https://s.jina.ai/FIFA%20World%20Cup%202026%20Golden%20Boot%20goals%20assists",parser:"search"}];
const $=id=>document.getElementById(id);
function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function noCacheUrl(url){const u=new URL(url);u.searchParams.set("_refresh",`${Date.now()}-${Math.random().toString(16).slice(2)}`);return u.toString()}
async function fetchText(url){const r=await fetch(noCacheUrl(url),{cache:"no-store",headers:{"Cache-Control":"no-cache, no-store, must-revalidate",Pragma:"no-cache",Expires:"0"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text()}
function cleanLine(line){return String(line||"").replace(/!\[[^\]]*\]\([^)]+\)/g,"").replace(/\[[^\]]*\]\([^)]+\)/g,"").replace(/[*_`#>|]/g,"").replace(/\s+/g," ").trim()}
function isNoiseLine(line){if(!line)return true;if(/^(image|read more|see all|rank|player|goals|assists)$/i.test(line))return true;if(/^(fw|mf|df|gk|goalkeeper|defender|midfielder|forward)$/i.test(line))return true;if(/^[A-Z]{2,4}$/.test(line))return true;if(/^[A-Z]{2,4}\s+(FW|MF|DF|GK)$/i.test(line))return true;if(/^flag/i.test(line))return true;return false}
function isLikelyName(line){if(isNoiseLine(line))return false;if(/^\d+(st|nd|rd|th)?$/i.test(line))return false;if(/^\d+$/.test(line))return false;if(/^\d+\s+(goals?|assists?)$/i.test(line))return false;if(/^(adidas golden boot|assists|passes|clean sheets|attempts at goal|player statistics)$/i.test(line))return false;return /[A-Za-zÀ-ÖØ-öø-ÿ]/.test(line)}
function extractNumberBeforeWord(lines,start,word,maxLookahead=8){const pattern=new RegExp(`(\\d+)\\s+${word}s?`,"i");for(let i=start;i<Math.min(lines.length,start+maxLookahead);i++){const m=lines[i].match(pattern);if(m)return Number(m[1])}return null}
function normalizePlayer(p){return{rank:Number(p.rank),name:String(p.name||"").trim(),goals:Number(p.goals||0),assists:Number(p.assists||0)}}
function dedupeAndSort(players){const map=new Map();for(const raw of players){const p=normalizePlayer(raw);if(!p.name||!Number.isFinite(p.goals))continue;const key=p.name.toLowerCase();const cur=map.get(key);if(!cur||p.goals>cur.goals||(p.goals===cur.goals&&p.assists>cur.assists))map.set(key,p)}return[...map.values()].sort((a,b)=>b.goals-a.goals||b.assists-a.assists||a.rank-b.rank||a.name.localeCompare(b.name)).map((p,i)=>({...p,rank:i+1}))}
function isolateGoldenBootBlock(text){const lower=text.toLowerCase();let start=lower.indexOf("adidas golden boot");if(start<0)start=lower.indexOf("golden boot");if(start<0)return text;let end=lower.indexOf("\nassists",start+250);if(end<0)end=lower.indexOf("\npasses",start+250);if(end<0)end=lower.indexOf("\nclean sheets",start+250);if(end<0)end=Math.min(text.length,start+7000);return text.slice(start,end)}
function parseFifaGoldenBoot(text){const block=isolateGoldenBootBlock(text);const lines=block.split(/\r?\n/).map(cleanLine).filter(Boolean);const players=[];for(let i=0;i<lines.length;i++){if(/^1st$/i.test(lines[i])){let name="";for(let j=i+1;j<Math.min(lines.length,i+6);j++){if(isLikelyName(lines[j])){name=lines[j];break}}const goals=extractNumberBeforeWord(lines,i,"goal",10);const assists=extractNumberBeforeWord(lines,i,"assist",12)??0;if(name&&goals!==null)players.push({rank:1,name,goals,assists})}}
for(let i=0;i<lines.length;i++){const rm=lines[i].match(/^(\d+)$/);if(!rm)continue;const rank=Number(rm[1]);if(!Number.isFinite(rank)||rank<1||rank>50)continue;let name="",ni=-1;for(let j=i+1;j<Math.min(lines.length,i+8);j++){if(isLikelyName(lines[j])){name=lines[j];ni=j;break}}if(!name)continue;const nums=[];for(let j=ni+1;j<Math.min(lines.length,ni+10);j++){if(/^\d+$/.test(lines[j]))nums.push(Number(lines[j]));const g=lines[j].match(/^(\d+)\s+goals?$/i);const a=lines[j].match(/^(\d+)\s+assists?$/i);if(g)nums[0]=Number(g[1]);if(a)nums[1]=Number(a[1]);if(nums.length>=2)break}if(nums.length>=1)players.push({rank,name,goals:nums[0],assists:nums[1]??0})}
const rg=/([A-ZÀ-ÖØ-öø-ÿ][A-Za-zÀ-ÖØ-öø-ÿ'. -]{3,60})\s+(?:[A-Z]{2,4}\s+)?(?:FW|MF|DF|GK)?\s+(\d+)\s+goals?\s+(\d+)\s+assists?/gi;let m;while((m=rg.exec(block))){const name=cleanLine(m[1]);if(isLikelyName(name))players.push({rank:999,name,goals:Number(m[2]),assists:Number(m[3])})}return dedupeAndSort(players)}
function parseSearchGoldenBoot(text){const players=[];const joined=text.split(/\r?\n/).map(cleanLine).filter(Boolean).join(" ");const regex=/([A-ZÀ-ÖØ-öø-ÿ][A-Za-zÀ-ÖØ-öø-ÿ'. -]{3,60})\s+(?:has|with|on|—|-|:)?\s*(\d+)\s+goals?(?:[^.]{0,80}?(\d+)\s+assists?)?/gi;let m;while((m=regex.exec(joined))){const name=cleanLine(m[1]).replace(/^(and|with|while)\s+/i,"");if(isLikelyName(name)&&!/world cup|golden boot|fifa/i.test(name))players.push({rank:999,name,goals:Number(m[2]),assists:Number(m[3]||0)})}return dedupeAndSort(players)}
async function loadGoldenBoot(){const btn=$("refreshBtn");btn.disabled=true;$("statusText").textContent="Refreshing…";$("leaderCard").innerHTML="";$("goldenBootList").innerHTML='<div class="empty">Fetching Golden Boot data…</div>';$("sourceText").textContent="Source: checking public sources…";$("rowCount").textContent="—";const errors=[];for(const source of SOURCES){try{const text=await fetchText(source.url);const players=source.parser==="search"?parseSearchGoldenBoot(text):parseFifaGoldenBoot(text);if(players.length){renderGoldenBoot(players,source.label);$("statusText").textContent="Loaded";$("lastUpdated").textContent=new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"medium"}).format(new Date());btn.disabled=false;return}errors.push(`${source.label}: no Golden Boot rows parsed`)}catch(e){console.warn(source.label,e);errors.push(`${source.label}: ${e.message}`)}}$("statusText").textContent="Unavailable";$("sourceText").textContent="Source: none loaded";$("goldenBootList").innerHTML=`<div class="error">Could not load Golden Boot data from the free public sources.<br>${escapeHtml(errors.join(" · "))}</div>`;btn.disabled=false}
function plural(n,word){return `${n} ${word}${Number(n)===1?"":"s"}`}
function renderGoldenBoot(players,label){const top=players[0];$("sourceText").textContent=`Source: ${label}`;$("rowCount").textContent=`${players.length} players`;$("leaderCard").innerHTML=`<article class="leader"><span class="rank-badge">1</span><div><div class="player-name">${escapeHtml(top.name)}</div><div class="player-meta">Current Golden Boot leader</div></div><div class="scorebox"><div class="goals">${escapeHtml(plural(top.goals,"goal"))}</div><div class="assists">${escapeHtml(plural(top.assists,"assist"))}</div></div></article>`;$("goldenBootList").innerHTML=players.map(p=>`<article class="row"><span class="rank">${escapeHtml(p.rank)}</span><strong>${escapeHtml(p.name)}</strong><span class="stat">${escapeHtml(plural(p.goals,"goal"))}</span><span class="stat">${escapeHtml(plural(p.assists,"assist"))}</span></article>`).join("")}
function setup(){$("refreshBtn").addEventListener("click",loadGoldenBoot);loadGoldenBoot()}document.addEventListener("DOMContentLoaded",setup);
